version = 1
SPDX-PackageName = "portal-ui-lib"
SPDX-PackageDownloadLocation = "https://github.com/openmfp/portal-ui-lib"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and openMFP contributors and portal contributors."
SPDX-License-Identifier = "Apache-2.0"
