export const ERROR_COMPONENT_CONFIG = 'OPENMFP_ERROR_COMPONENT_CONFIG';

export const THEMING_SERVICE = 'OPENMFP_THEMING_SERVICE';

export const LUIGI_STATIC_SETTINGS_CONFIG_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_STATIC_SETTINGS_CONFIG_SERVICE';
export const LUIGI_CUSTOM_MESSAGE_LISTENERS_INJECTION_TOKEN =
  'OPENMFP_LUIGI_CUSTOM_MESSAGE_LISTENERS';
export const LUIGI_GLOBAL_SEARCH_CONFIG_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_GLOBAL_SEARCH_CONFIG_SERVICE';
export const LUIGI_APP_SWITCHER_CONFIG_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_APP_SWITCHER_CONFIG_SERVICE';
export const LUIGI_USER_PROFILE_CONFIG_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_USER_PROFILE_CONFIG_SERVICE';
export const LUIGI_BREADCRUMB_CONFIG_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_BREADCRUMB_CONFIG_SERVICE';
export const LUIGI_NODE_CHANGE_HOOK_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_NODE_CHANGE_HOOK_CONFIG_SERVICE';
export const LUIGI_EXTENDED_GLOBAL_CONTEXT_CONFIG_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_NODES_EXTENDED_CONTEXT_SERVICE';

export const LOCAL_CONFIGURATION_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LOCAL_CONFIGURATION_SERVICE';
export const LUIGI_NODES_CUSTOM_GLOBAL_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_NODES_CUSTOM_GLOBAL_SERVICE';
export const LUIGI_CUSTOM_NODE_PROCESSING_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_CUSTOM_NODE_PROCESSING_SERVICE';
export const LUIGI_CUSTOM_NODE_CONTEXT_PROCESSING_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_CUSTOM_NODE_CONTEXT_PROCESSING_SERVICE';

export const LUIGI_AUTH_EVENTS_CALLBACKS_SERVICE_INJECTION_TOKEN =
  'OPENMFP_LUIGI_AUTH_EVENTS_CALLBACKS_SERVICE';

export const HEADER_BAR_CONFIG_SERVICE_INJECTION_TOKEN =
  'OPENMFP_HEADER_BAR_CONFIG_SERVICE';

export const UI_OPTIONS_INJECTION_TOKEN = 'OPENMFP_UI_OPTIONS';
