name: "Update License Metadata"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '32 16 * * 0'

jobs:
  license:
    concurrency:
      group: license-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
    uses: openmfp/gha/.github/workflows/job-license-metadata.yml@main
    secrets: inherit