name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@e3a13d61b71c77dc9412917c26bb1fa92bb86937 # main
    secrets: inherit
    with:
      publishFromDist: true
      environment: npmjs:@openmfp/portal-ui-lib
